package main

func init() {
	tpls.Append("gen:general",
		`// Note: This file is generated by gourd.
// If you want to re-generate this in the future, do not change it.

{{ template "package" . }}

import (
{{ template "imports" . }}
)
{{ template "code" . }}
	`)
}
