// Generated by gourd (version 0.1dev)
// Generated at 2015/11/02 19:14:57 (+0800)
// Note: If you want to re-generate this file in the future,
//       do not change it.

package main

import (
	"github.com/gourd/kit/store"
	"github.com/gourd/kit/store/upperio"
	"net/http"

	"log"
	"upper.io/db"
)

func init() {
	// define store provider with proxy
	store.Providers.DefineFunc("Post", func(r *http.Request) (s store.Store, err error) {
		return GetPostStore(r)
	})
}

// GetPostStore provides raw PostStore
func GetPostStore(r *http.Request) (s *PostStore, err error) {

	// obtain database
	db, err := upperio.Open(r, "default")
	if err != nil {
		return
	}

	// define store and return
	s = &PostStore{db}
	return
}

// PostStore serves generic CURD for type Post
// Generated by gourd CLI tool
type PostStore struct {
	Db db.Database
}

// Create a Post in the database, of the parent
func (s *PostStore) Create(
	cond store.Conds, ep store.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// apply random uuid string to string id

	// Marshal the item, if possible
	// (quick fix for upperio problem with db.Marshaler)
	if me, ok := ep.(db.Marshaler); ok {
		ep, err = me.MarshalDB()
		if err != nil {
			return
		}
	}

	// add the entity to collection

	id, err := coll.Append(ep)

	if err != nil {
		log.Printf("Error creating Post: %s", err.Error())
		err = store.ErrorInternal
		return
	}

	// apply the key to the entity
	e := ep.(*Post)
	e.ID = int32(id.(int64))

	return
}

// Search a Post by its condition(s)
func (s *PostStore) Search(
	q store.Query) store.Result {

	return upperio.NewResult(func() (res db.Result, err error) {
		// get collection
		coll, err := s.Coll()
		if err != nil {
			return
		}

		// retrieve entities by given query conditions
		conds := upperio.Conds(q.GetConds())
		if conds == nil {
			res = coll.Find()
		} else {
			res = coll.Find(conds)
		}

		// handle paging
		if q.GetOffset() != 0 {
			res = res.Skip(uint(q.GetOffset()))
		}
		if q.GetLimit() != 0 {
			res = res.Limit(uint(q.GetLimit()))
		}

		return
	})

}

// One returns the first Post matches condition(s)
func (s *PostStore) One(
	c store.Conds, ep store.EntityPtr) (err error) {

	// retrieve results from database
	l := &[]Post{}
	q := store.NewQuery().SetConds(c)

	// dump results into pointer of map / struct
	err = s.Search(q).All(l)
	if err != nil {
		return
	}

	// if not found, report
	if len(*l) == 0 {
		err = store.ErrorNotFound
		return
	}

	// assign the value of given point
	// to the first retrieved value
	(*ep.(*Post)) = (*l)[0]
	return nil
}

// Update Post on condition(s)
func (s *PostStore) Update(
	c store.Conds, ep store.EntityPtr) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// Marshal the item, if possible
	// (quick fix for upperio problem with db.Marshaler)
	if me, ok := ep.(db.Marshaler); ok {
		ep, err = me.MarshalDB()
		if err != nil {
			return
		}
	}

	// update the matched entities
	err = res.Update(ep)
	if err != nil {
		log.Printf("Error updating Post: %s", err.Error())
		err = store.ErrorInternal
	}
	return
}

// Delete Post on condition(s)
func (s *PostStore) Delete(
	c store.Conds) (err error) {

	// get collection
	coll, err := s.Coll()
	if err != nil {
		return
	}

	// get by condition and ignore the error
	cond, _ := c.GetMap()
	res := coll.Find(db.Cond(cond))

	// remove the matched entities
	err = res.Remove()
	if err != nil {
		log.Printf("Error deleting Post: %s", err.Error())
		err = store.ErrorInternal
	}
	return nil
}

// AllocEntity allocate memory for an entity
func (s *PostStore) AllocEntity() store.EntityPtr {
	return &Post{}
}

// AllocEntityList allocate memory for an entity list
func (s *PostStore) AllocEntityList() store.EntityListPtr {
	return &[]Post{}
}

// Len inspect the length of an entity list
func (s *PostStore) Len(pl store.EntityListPtr) int64 {
	el := pl.(*[]Post)
	return int64(len(*el))
}

// Coll return the raw upper.io collection
func (s *PostStore) Coll() (coll db.Collection, err error) {
	// get raw collection
	coll, err = s.Db.Collection("posts")
	if err != nil {
		log.Printf("Error connecting collection posts: %s",
			err.Error())
		err = store.ErrorInternal
	}
	return
}

// Close the database session that Post is using
func (s *PostStore) Close() error {
	return s.Db.Close()
}
