package main

import (
	"github.com/codegangsta/negroni"
	"github.com/gorilla/pat"
	"github.com/gourd/codec"
	"github.com/gourd/oauth2"
	"github.com/gourd/perm"
	"log"
	"net/http"
)

// MainHandler
//
// drafted gourd generated server
// will be generated by gourd CLI tool eventually
//
// Should also be a http.Handler that
// cound be tested by wrapping httptest sevrer
func MainHandler() http.Handler {

	// create router specific / independent middleware
	ch := &codec.Handler{}

	// oauth2 manager with default settings
	m := oauth2.NewManager()

	// provide access handlers to
	// NOTE: these are independent to router
	p := perm.NewMux()
	requireAccess := func(r *http.Request, perm string, info ...interface{}) error {
		log.Printf("Requesting permission to %s", perm)
		a, err := oauth2.GetAccess(r)
		if err == nil {
			log.Printf("Access: %#v", a)
		}
		return err
	}
	p.HandleFunc("create post", requireAccess)
	p.HandleFunc("load post", requireAccess)
	p.HandleFunc("list post", requireAccess)
	p.HandleFunc("update post", requireAccess)
	p.HandleFunc("delete post", requireAccess)

	// create router of the specific type
	rtr := pat.New()

	// add services rest to router
	PostServiceRest(rtr, "/api", "post", "posts")
	CommentServiceRest(rtr, "/api", "comment", "comments")
	oauth2.RoutePat(rtr, "/oauth", m.GetEndpoints())

	// add login form to router
	// TODO: need a way to inject templates for login form
	// NOTE: this will be generated if needed to be router specific
	//ah.ServeLogin(rtr, "/login")

	// create negroni middleware handler
	// with middlewares
	n := negroni.New()
	n.Use(negroni.Wrap(ch))
	n.Use(negroni.Wrap(m.Middleware()))
	n.Use(negroni.Wrap(p))

	// use router in negroni
	n.UseHandler(rtr)

	return n
}
