package main

import (
	"github.com/codegangsta/negroni"
	"github.com/gorilla/pat"
	"github.com/gourd/codec"
	"github.com/gourd/oauth2"
	"github.com/gourd/perm"
	"github.com/gourd/service/upperio"
	"log"
	"net/http"
	"time"
	"upper.io/db/sqlite"
)

// getServer
//
// drafted gourd generated server
// will be generated by gourd CLI tool eventually
//
// Should also be a http.Handler that
// cound be tested by wrapping httptest sevrer
func gourdServer() (h http.Handler) {

	// define db
	upperio.Define("default", sqlite.Adapter, sqlite.ConnectionURL{
		Database: `./data/sqlite3.db`,
	})

	// create router specific / independent middleware
	ch := &codec.Handler{}

	// oauth2 manager with default settings
	m := oauth2.NewManager()

	// provide access handlers to
	// NOTE: these are independent to router
	p := perm.NewMux()
	p.HandleFunc("create post", func(r *http.Request, perm string, info ...interface{}) error {
		log.Printf("Requesting permission to create post")
		return nil
	})
	p.HandleFunc("load post", func(r *http.Request, perm string, info ...interface{}) error {
		log.Printf("Requesting permission to load post")
		return nil
	})
	p.HandleFunc("update post", func(r *http.Request, perm string, info ...interface{}) error {
		log.Printf("Requesting permission to update post")
		return nil
	})
	p.HandleFunc("delete post", func(r *http.Request, perm string, info ...interface{}) error {
		log.Printf("Requesting permission to delete post")
		return nil
	})

	// create router of the specific type
	rtr := pat.New()

	// add services rest to router
	PostServiceRest(rtr, "/api", "post", "posts")
	CommentServiceRest(rtr, "/api", "comment", "comments")
	oauth2.RoutePat(rtr, "/oauth", m.GetEndpoints())

	// add login form to router
	// TODO: need a way to inject templates for login form
	// NOTE: this will be generated if needed to be router specific
	//ah.ServeLogin(rtr, "/login")

	// create negroni middleware handler
	// with middlewares
	n := negroni.New()
	n.Use(negroni.Wrap(ch))
	n.Use(negroni.Wrap(m.Middleware()))
	n.Use(negroni.Wrap(p))

	// use router in negroni
	n.UseHandler(rtr)

	return n
}

// gourdMain
//
// gourd generated main
// feel free to copy the code and change
func gourdMain() {
	s := &http.Server{
		Addr:           ":8080",
		Handler:        gourdServer(),
		ReadTimeout:    10 * time.Second,
		WriteTimeout:   10 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}
	log.Fatal(s.ListenAndServe())
}
