package main

import (
	"encoding/json"
	"github.com/codegangsta/negroni"
	"github.com/gorilla/pat"
	"github.com/gourd/service"
	"log"
	"net/http"
	"upper.io/db"
	"upper.io/db/sqlite"
)

// dummy rest binder
func Rest(r *pat.Router, base, noun, nounp string, s service.Service) {

	// define paths
	p := base + "/" + nounp
	ep := base + "/" + noun + "/{id}"

	log.Printf("REST path: %s", p)

	// Create
	r.Post(p, func(w http.ResponseWriter, r *http.Request) {
		var err error

		// allocate entity
		e := s.AllocEntity()

		// assign encoder and decoder
		respEnc := json.NewEncoder(w)
		reqtDec := json.NewDecoder(r.Body)

		// decode request
		err = reqtDec.Decode(e)
		if err != nil {
			log.Printf("Error JSON Unmarshal: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Cannot decode request",
			})
			return
		}

		// create entity
		err = s.Create(nil, e)
		if err != nil {
			log.Printf("Error Creating Post: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Failed to create entity",
			})
			return
		}

		// encode response
		respEnc.Encode(map[string]interface{}{
			"status": "success",
			"code":   http.StatusOK,
			nounp:    []interface{}{e},
		})
	})

	// Retrieve single
	r.Get(ep, func(w http.ResponseWriter, r *http.Request) {
		var err error

		// allocate memory for variables
		el := s.AllocEntityList()

		// assign encoder and decoder
		respEnc := json.NewEncoder(w)

		// retrieve
		id := r.URL.Query().Get(":id") // will change
		cond := service.NewConds().Add("id", id)
		err = s.Search(cond, el)
		if err != nil {
			log.Printf("Error searching Post: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Failed to find entity",
			})
			return
		}

		// encode response
		pl := el.(*[]Post)
		if len(*pl) == 0 {
			respEnc.Encode(map[string]interface{}{
				"status": "error",
				"code":   http.StatusNotFound,
			})
		} else {
			respEnc.Encode(map[string]interface{}{
				"status": "success",
				"code":   http.StatusOK,
				nounp:    el,
			})
		}
	})

	// TODO: Retrieve list

	// Update
	r.Put(ep, func(w http.ResponseWriter, r *http.Request) {
		var err error

		// allocate memory for variables
		e := s.AllocEntity()
		el := s.AllocEntityList()

		// assign encoder and decoder
		respEnc := json.NewEncoder(w)
		reqtDec := json.NewDecoder(r.Body)

		// decode request
		err = reqtDec.Decode(e)
		if err != nil {
			log.Printf("Error JSON Unmarshal: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Cannot decode request",
			})
			return
		}

		// find the content of the id
		id := r.URL.Query().Get(":id")
		cond := service.NewConds().Add("id", id)
		err = s.Search(cond, el)
		if err != nil {
			log.Printf("Error searching Post: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Failed to find entity",
			})
			return
		}

		// update entity
		s.Update(cond, e)

		// encode response
		respEnc.Encode(map[string]interface{}{
			"status": "success",
			"code":   http.StatusOK,
			noun:     e,
		})
	})

	// Delete
	r.Delete(ep, func(w http.ResponseWriter, r *http.Request) {
		var err error

		// allocate memory for variables
		e := s.AllocEntity()
		el := s.AllocEntityList()

		// assign encoder and decoder
		respEnc := json.NewEncoder(w)

		// find the content of the id
		id := r.URL.Query().Get(":id")
		cond := service.NewConds().Add("id", id)
		err = s.Search(cond, el)
		if err != nil {
			log.Printf("Error searching Post: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    http.StatusBadRequest,
				"message": "Failed to find entity",
			})
			return
		}

		// delete entity
		s.Delete(cond)

		// encode response
		respEnc.Encode(map[string]interface{}{
			"status": "success",
			"code":   http.StatusOK,
			noun:     e,
		})
	})

}

// getServer
//
// drafted gourd generated server
// will be generated by gourd CLI tool eventually
//
// Should also be a http.Handler that
// cound be tested by wrapping httptest sevrer
func gourdServer() (n *negroni.Negroni) {

	// define db
	db, err := db.Open(sqlite.Adapter, sqlite.ConnectionURL{
		Database: `./data/sqlite3.db`,
	})
	if err != nil {
		panic(err)
	}

	// create router specific / independent middleware
	//ep := &EncoderPrvdr{}
	//cp := &GorillaPatCondPrvdr{}
	//ap := &OAuth2Prvdr{}

	// provide services to auth provider
	//ap.UseServices(ClientService{db}, AuthService{db}, AccessService{db})

	// create router of the specific type
	r := pat.New()

	// create negroni middleware handler
	// with middlewares
	n = negroni.New()
	//n := negroni.New(
	//	negroni.Wrap(ep),
	//	negroni.Wrap(cp),
	//	negroni.Wrap(ap.Mid()))

	// add services rest to router
	Rest(r, "/api", "post", "posts", &PostService{db})
	Rest(r, "/api", "comment", "comments", &CommentService{db})

	// add oauth2 endpoints
	//AddOAuth2(r, "/oauth", ap)

	// use router in negroni
	n.UseHandler(r)

	return
}

// gourdMain
//
// gourd generated main
// feel free to copy the code and change
func gourdMain() {
	s := gourdServer()
	if s != nil {
		s.Run(":8080") // negroni specific
	}
}
