package main

import (
	"log"
	"net/http"

	"github.com/codegangsta/negroni"
	"github.com/gorilla/pat"
	gourdctx "github.com/gourd/kit/context"
	"github.com/gourd/kit/oauth2"
	"github.com/gourd/kit/perm"
	"golang.org/x/net/context"
)

// MainHandler
//
// drafted gourd generated server
// will be generated by gourd CLI tool eventually
//
// Should also be a http.Handler that
// cound be tested by wrapping httptest sevrer
func MainHandler() http.Handler {

	// oauth2 manager with default settings
	m := oauth2.NewManager()

	// provide access handlers to
	// NOTE: these are independent to router
	p := perm.NewMux()
	requireAccess := func(ctx context.Context, perm string, info ...interface{}) (err error) {
		// get access from context HTTP Request
		log.Printf("Requesting permission to %s", perm)
		a, err := oauth2.GetAccess(gourdctx.HTTPRequest(ctx))
		if err == nil {
			log.Printf("Access: %#v", a)
		}
		return
	}
	p.HandleFunc("create post", requireAccess)
	p.HandleFunc("retrieve post", requireAccess)
	p.HandleFunc("list post", requireAccess)
	p.HandleFunc("update post", requireAccess)
	p.HandleFunc("delete post", requireAccess)

	// create router of the specific type
	rtr := pat.New()

	// add store rest to router
	PostStoreRest(rtr, p, "/api", "post", "posts")
	CommentStoreRest(rtr, p, "/api", "comment", "comments")
	oauth2.RoutePat(rtr, "/oauth", m.GetEndpoints())

	// add login form to router
	// TODO: need a way to inject templates for login form
	// NOTE: this will be generated if needed to be router specific
	//ah.ServeLogin(rtr, "/login")

	// create negroni middleware handler
	// with middlewares
	n := negroni.New()
	n.Use(negroni.Wrap(m.Middleware()))

	// use router in negroni
	n.UseHandler(rtr)

	return n
}
