package main

import (
	"encoding/json"
	"github.com/codegangsta/negroni"
	"github.com/gorilla/pat"
	"github.com/gourd/service"
	"log"
	"net/http"
	"upper.io/db"
	"upper.io/db/sqlite"
)

// dummy rest binder
func Rest(r *pat.Router, p string, ep string, s service.Service) {

	log.Printf("REST path: %s", p)

	r.Post(p, func(w http.ResponseWriter, r *http.Request) {
		var err error

		// allocate entity
		e := s.AllocEntity()

		// assign encoder and decoder
		respEnc := json.NewEncoder(w)
		reqtDec := json.NewDecoder(r.Body)

		// decode request
		err = reqtDec.Decode(e)
		if err != nil {
			log.Printf("Error JSON Unmarshal: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    400,
				"message": "Cannot decode request",
			})
			return
		}

		// create entity
		err = s.Create(nil, e)
		if err != nil {
			log.Printf("Error Creating Post: ", err)
			respEnc.Encode(map[string]interface{}{
				"status":  "error",
				"code":    400,
				"message": "Failed to create entity",
			})
			return
		}

		// encode response
		respEnc.Encode(map[string]interface{}{
			"status": "success",
			"code":   200,
			"posts":  []interface{}{e},
		})
	})
}

// getServer
//
// drafted gourd generated server
// will be generated by gourd CLI tool eventually
//
// Should also be a http.Handler that
// cound be tested by wrapping httptest sevrer
func gourdServer() (n *negroni.Negroni) {

	// define db
	db, err := db.Open(sqlite.Adapter, sqlite.ConnectionURL{
		Database: `./data/sqlite3.db`,
	})
	if err != nil {
		panic(err)
	}

	// create router specific / independent middleware
	//ep := &EncoderPrvdr{}
	//cp := &GorillaPatCondPrvdr{}
	//ap := &OAuth2Prvdr{}

	// provide services to auth provider
	//ap.UseServices(ClientService{db}, AuthService{db}, AccessService{db})

	// create router of the specific type
	r := pat.New()

	// create negroni middleware handler
	// with middlewares
	n = negroni.New()
	//n := negroni.New(
	//	negroni.Wrap(ep),
	//	negroni.Wrap(cp),
	//	negroni.Wrap(ap.Mid()))

	// add services rest to router
	Rest(r, "/api/posts", "/api/posts/{id}", &PostService{db})
	Rest(r, "/api/comments", "/api/comments/{id}", &CommentService{db})

	// add oauth2 endpoints
	//AddOAuth2(r, "/oauth", ap)

	// use router in negroni
	n.UseHandler(r)

	return
}

// gourdMain
//
// gourd generated main
// feel free to copy the code and change
func gourdMain() {
	s := gourdServer()
	if s != nil {
		s.Run(":8080") // negroni specific
	}
}
